# Generated by Edison. Source this file in a POSIX shell.
EDISON_SHIMS_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE:-$0}")" && pwd)"
export EDISON_SHIMS_DIR
case ":${PATH:-}:" in
  *":${EDISON_SHIMS_DIR}:"*) ;;
  *) export PATH="${EDISON_SHIMS_DIR}:${PATH:-}" ;;
esac
